export default [
   {
      id: 1,
      college: "Narayana Jr college",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "applied",
      cType: "10+2",
      rStatus: 4,
      pStatus: "paid",
   },
   {
      id: 2,
      college: "nothing",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "pending",
      cType: "10+2",
      rStatus: 2,
      pStatus: "pending",
   },
   {
      id: 3,
      college: "Narayana Jr college",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "applied",
      cType: "10+2",
      rStatus: 4,
      pStatus: "paid",
   },
   {
      id: 4,
      college: "nothing",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "applied",
      cType: "10+2",
      rStatus: 2,
      pStatus: "pending",
   },
   {
      id: 5,
      college: "Narayana Jr college",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "applied",
      cType: "10+2",
      rStatus: 4,
      pStatus: "paid",
   },
   {
      id: 6,
      college: "nothing",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "pending",
      cType: "10+2",
      rStatus: 2,
      pStatus: "pending",
   },
   {
      id: 7,
      college: "Narayana Jr college",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "applied",
      cType: "10+2",
      rStatus: 4,
      pStatus: "paid",
   },
   {
      id: 8,
      college: "nothing",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "applied",
      cType: "10+2",
      rStatus: 2,
      pStatus: "pending",
   },
   {
      id: 9,
      college: "Narayana Jr college",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "applied",
      cType: "10+2",
      rStatus: 4,
      pStatus: "paid",
   },
   {
      id: 10,
      college: "nothing",
      city: "Hyderabad",
      totalAdmission: 367,
      appliedAdmission: 150,
      oStatus: "applied",
      cType: "10+2",
      rStatus: 2,
      pStatus: "pending",
   },
];
